name: geosnap
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - giddy >=2.2.1
  - libpysal
  - spenc
  - cenpy
  - geopandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pyarrow >=0.14.1
  - appdirs
  - dash
  - dash-bootstrap-components
  - palettable
  - pip
  - tqdm
  - quilt3 >=3.1.11
  - xlrd
  - region >=0.2.0
  - tobler >=0.2.1